/** Appendix B: stable error codes, HTTP status and localised default messages. */
export const ERROR_CATALOG = {
  VALIDATION_ERROR: { status: 400, en: 'The request is invalid.', de: 'Die Anfrage ist ungültig.' },
  TOKEN_INVALID: { status: 400, en: 'The link is invalid, used or expired.', de: 'Der Link ist ungültig, bereits verwendet oder abgelaufen.' },
  PAIRING_CODE_INVALID: { status: 400, en: 'The pairing code is invalid, used or expired.', de: 'Der Kopplungscode ist ungültig, bereits verwendet oder abgelaufen.' },
  UNAUTHENTICATED: { status: 401, en: 'Authentication required.', de: 'Anmeldung erforderlich.' },
  TOKEN_EXPIRED: { status: 401, en: 'The session token has expired.', de: 'Das Sitzungstoken ist abgelaufen.' },
  INVALID_CREDENTIALS: { status: 401, en: 'Login or password is wrong.', de: 'Anmeldename oder Passwort ist falsch.' },
  DEVICE_UNAUTHORIZED: { status: 401, en: 'This device is not authorised.', de: 'Dieses Gerät ist nicht berechtigt.' },
  INVALID_PIN: { status: 401, en: 'The PIN is wrong.', de: 'Die PIN ist falsch.' },
  PUNCH_TOKEN_INVALID: { status: 401, en: 'Please enter your PIN again.', de: 'Bitte die PIN erneut eingeben.' },
  FORBIDDEN: { status: 403, en: 'You are not allowed to do this.', de: 'Dazu fehlt die Berechtigung.' },
  CSRF_REJECTED: { status: 403, en: 'Request rejected (CSRF protection).', de: 'Anfrage abgelehnt (CSRF-Schutz).' },
  RESOURCE_NOT_FOUND: { status: 404, en: 'Not found.', de: 'Nicht gefunden.' },
  EMPLOYEE_ALREADY_SCHEDULED: { status: 409, en: 'The employee is already scheduled for this.', de: 'Die Person ist dafür bereits eingeplant.' },
  SHIFT_OVERLAPS_EXISTING: { status: 409, en: 'The shift overlaps another shift of this employee.', de: 'Die Schicht überschneidet sich mit einer anderen Schicht dieser Person.' },
  DUPLICATE_RESOURCE: { status: 409, en: 'This already exists.', de: 'Das existiert bereits.' },
  RESOURCE_IN_USE: { status: 409, en: 'This is still in use.', de: 'Das wird noch verwendet.' },
  TIME_OFF_OVERLAP: { status: 409, en: 'Overlaps an existing absence or wish.', de: 'Überschneidet sich mit einer bestehenden Abwesenheit oder einem Wunsch.' },
  TIME_OFF_CONFLICTS_WITH_SCHEDULE: { status: 409, en: 'The absence covers roster entries.', de: 'Die Abwesenheit überdeckt Dienstplaneinträge.' },
  PUBLISH_CONFLICTS: { status: 409, en: 'Some drafts violate roster rules; nothing was published.', de: 'Einige Entwürfe verletzen Regeln; nichts wurde veröffentlicht.' },
  BULK_FAILED: { status: 409, en: 'At least one item failed; nothing was saved.', de: 'Mindestens ein Eintrag ist fehlgeschlagen; nichts wurde gespeichert.' },
  INVALID_PUNCH_STATE: { status: 409, en: 'This action is not possible right now.', de: 'Diese Aktion ist gerade nicht möglich.' },
  ENTRY_NEEDS_REVIEW: { status: 409, en: 'Your last time entry needs a manager review.', de: 'Dein letzter Zeiteintrag muss von einer Führungskraft geprüft werden.' },
  TIME_ENTRY_OVERLAP: { status: 409, en: 'The time entry overlaps another entry.', de: 'Der Zeiteintrag überschneidet sich mit einem anderen.' },
  PRECONDITION_FAILED: { status: 412, en: 'The record was changed by someone else.', de: 'Der Datensatz wurde zwischenzeitlich geändert.' },
  EMPLOYEE_ON_TIME_OFF: { status: 422, en: 'The employee has an approved absence on this date.', de: 'Für dieses Datum liegt eine genehmigte Abwesenheit vor.' },
  EMPLOYEE_NOT_IN_DEPARTMENT: { status: 422, en: "The employee does not work in this shift's department.", de: 'Die Person gehört nicht zur Abteilung dieser Schicht.' },
  EMPLOYEE_INACTIVE: { status: 422, en: 'The employee is no longer active.', de: 'Die Person ist nicht mehr aktiv.' },
  MAX_SHIFTS_PER_DAY_EXCEEDED: { status: 422, en: 'Too many shifts on this day.', de: 'Zu viele Schichten an diesem Tag.' },
  MINOR_PROTECTION_VIOLATION: { status: 422, en: 'Youth employment protection rules are violated.', de: 'Regeln des Jugendarbeitsschutzes werden verletzt.' },
  LEAVE_BLACKOUT: { status: 422, en: 'Leave is blocked in this period.', de: 'In diesem Zeitraum ist Urlaub gesperrt.' },
  WISH_DEADLINE_PASSED: { status: 422, en: 'Wishes for this date are closed.', de: 'Wünsche für dieses Datum sind nicht mehr möglich.' },
  UNPLANNED_REASON_REQUIRED: { status: 422, en: 'Clocking in without a planned shift needs a reason.', de: 'Das Einstempeln ohne geplante Schicht erfordert eine Begründung.' },
  OVERRIDE_REASON_REQUIRED: { status: 422, en: 'A written reason is required to save this.', de: 'Zum Speichern ist eine schriftliche Begründung nötig.' },
  PAYROLL_MAPPING_INCOMPLETE: { status: 422, en: 'The DATEV mapping is incomplete.', de: 'Die DATEV-Zuordnung ist unvollständig.' },
  EMPLOYEE_NOT_ASSIGNED_TO_HOTEL: { status: 422, en: 'The employee is not assigned to this hotel on that date.', de: 'Die Person ist an diesem Datum nicht diesem Hotel zugeordnet.' },
  SCHEDULE_DATE_IN_PAST: { status: 422, en: 'The date is in the past.', de: 'Das Datum liegt in der Vergangenheit.' },
  ALLOWANCE_EXCEEDED: { status: 422, en: 'Not enough vacation days left.', de: 'Nicht genug Urlaubstage übrig.' },
  NO_WORKING_DAYS_IN_RANGE: { status: 422, en: 'The range contains no working days.', de: 'Der Zeitraum enthält keine Arbeitstage.' },
  INVALID_STATUS_TRANSITION: { status: 422, en: 'This status change is not allowed.', de: 'Dieser Statuswechsel ist nicht erlaubt.' },
  RANGE_TOO_LARGE: { status: 422, en: 'The date range is too large (max 62 days).', de: 'Der Zeitraum ist zu groß (max. 62 Tage).' },
  RETENTION_NOT_ELAPSED: { status: 422, en: 'The retention period has not elapsed yet.', de: 'Die Aufbewahrungsfrist ist noch nicht abgelaufen.' },
  ACCOUNT_LOCKED: { status: 423, en: 'The account is temporarily locked.', de: 'Das Konto ist vorübergehend gesperrt.' },
  PIN_LOCKED: { status: 423, en: 'The PIN is temporarily locked.', de: 'Die PIN ist vorübergehend gesperrt.' },
  PERIOD_LOCKED: { status: 423, en: 'This period is locked for payroll.', de: 'Dieser Zeitraum ist für die Lohnabrechnung gesperrt.' },
  RATE_LIMITED: { status: 429, en: 'Too many requests.', de: 'Zu viele Anfragen.' },
  INTERNAL_ERROR: { status: 500, en: 'Unexpected error.', de: 'Unerwarteter Fehler.' },
} as const;

export type ErrorCode = keyof typeof ERROR_CATALOG;
export type Lang = 'de' | 'en';
