/** English UI texts; the German source string is the key. Completeness is enforced by tests/unit/i18n.test.ts. */
export const EN: Record<string, string> = {
  '+ {n} beantragt': '+ {n} requested', Abbrechen: 'Cancel', Abgelehnt: 'Rejected', Ablehnen: 'Reject', 'Ablehnen?': 'Reject?', Abmelden: 'Sign out',
  Abteilung: 'Department', Abteilungen: 'Departments', Abwesend: 'Absent', 'Abwesenheit entschieden': 'Absence decided', Abwesenheiten: 'Absences',
  'Achtung: Jugendschutz.': 'Attention: youth protection rules.', Aktiv: 'Active', 'Aktuelles Passwort': 'Current password', Alle: 'All',
  'Alle Abteilungen': 'All departments', 'Alle Erwarteten sind da.': 'Everyone due has arrived.', 'Alle Hotels': 'All hotels', 'Alle als gelesen markieren': 'Mark all as read',
  'Als Entwurf kopieren': 'Copy as draft', 'An deine Hotels gerichtet': 'Addressed to your hotels', 'Angemeldete Geräte': 'Signed-in devices', Anlegen: 'Create',
  Anmelden: 'Sign in', 'Antrag gesendet.': 'Request sent.', Anträge: 'Requests', Antwort: 'Reply', 'Antwort auf Frage': 'Answer to a question',
  'Antwort auf deine Frage': 'Answer to your question', 'Antwort …': 'Reply …', Anwesenheit: 'Attendance', Arbeitstage: 'Work days', 'Arbeitszeit entschieden': 'Working time decided',
  'Arbeitszeit wartet auf Freigabe': 'Working time awaits approval', Arbeitszeitkonto: 'Time account', Art: 'Type', 'Atteste fehlen': 'Certificates missing',
  'Auf dem Tablet {url} öffnen und den Code eingeben.': 'Open {url} on the tablet and enter the code.', Ausgeschieden: 'Left the company', Ausgestempelt: 'Clocked out',
  'Ausgestempelt {time}': 'Clocked out {time}', Ausstempeln: 'Clock out', 'Ausstempeln {t}': 'Clock out {t}', Austritt: 'Leaving date', Auswertung: 'Analytics',
  Auszubildende: 'Apprentice', 'Automatisch mit Plan-Zeit geschlossen': 'Closed automatically with planned time', Beantragen: 'Request', Beantragt: 'Requested',
  Beantwortet: 'Answered', Bearbeiten: 'Edit', Begründung: 'Reason', 'Begründung (falls nötig)': 'Reason (if required)', 'Begründung (nötig)': 'Reason (required)',
  'Begründung (optional)': 'Reason (optional)', Berufsschule: 'Vocational school', Beschäftigung: 'Employment', Besetzung: 'Coverage', Bestätigen: 'Confirm', Betreff: 'Subject',
  Betroffene: 'Affected', Beurlaubt: 'On leave', Bis: 'To', 'Bitte PIN eingeben': 'Please enter your PIN',
  'Bitte keine Diagnose angeben. Ab dem 4. Tag brauchst du eine Krankschreibung.': 'Please do not state a diagnosis. From day 4 you need a medical certificate.',
  'Bitte schreibe hier keine Gesundheitsdaten. Antworten sehen nur du und die Leitung deines Hotels.': 'Please do not write health data here. Only you and your hotel management see the answers.',
  Bradford: 'Bradford', Datum: 'Date', 'Davon dieses Jahr noch übrig': 'Of which left this year', 'Dein Abwesenheitsantrag wurde entschieden': 'Your absence request was decided',
  'Dein Dienst am {date} wurde entfernt': 'Your shift on {date} was removed', 'Dein Dienst am {date} wurde geändert': 'Your shift on {date} was changed',
  'Dein Wunsch wurde entschieden': 'Your wish was decided', 'Deine Leitung antwortet hier': 'Your management answers here',
  'Deine Leitung erzeugt unter „Tablet & Export“ einen Kopplungscode.': 'Your manager creates a pairing code under “Tablet & Export”.',
  'Deine Zeitkorrektur wurde entschieden': 'Your time correction was decided', 'Deine ungeplante Arbeitszeit wurde entschieden': 'Your unplanned working time was decided',
  'Der Eintrag wird ausgeblendet, die Zeithistorie bleibt erhalten. Mit zukünftigen Diensten ist das Löschen nicht möglich.': 'The record is hidden and the time history is kept. Deleting is not possible while future shifts exist.',
  'Der Link ist ungültig.': 'The link is invalid.', 'Der Rest wird in jedem neuen Jahr automatisch übertragen.': 'What is left is carried over automatically every new year.',
  'Der Zeitraum ist noch nicht gesperrt.': 'The period is not locked yet.', Di: 'Tue', 'Die Passwörter stimmen nicht überein.': 'The passwords do not match.',
  'Die Sperre kann nur nach vorne verschoben werden.': 'The lock can only be moved forward.',
  'Die Uhrzeit kommt vom Server. Deine geplante Pause wird automatisch abgezogen.': 'The time comes from the server. Your scheduled break is deducted automatically.',
  Dienst: 'Shift', 'Dienst hinzufügen': 'Add shift', 'Dienst entfernt': 'Shift removed', 'Dienst geändert': 'Shift changed', Dienstplan: 'Roster', 'Dienstplan & Zeiterfassung': 'Roster & Attendance',
  'Dienstplan veröffentlicht': 'Roster published', 'Dienstplan {hotel} veröffentlicht bis {date}': 'Roster {hotel} published until {date}', 'Dienstplan {hotel}: noch nichts veröffentlicht': 'Roster {hotel}: nothing published yet', 'Dies ist ein Stempel-Tablet →': 'This is a clock-in tablet →',
  'Diese Woche': 'This week', 'Dieser Monat': 'This month', 'Dieses Gerät': 'This device', Differenz: 'Difference', Do: 'Thu', 'Drucken / PDF': 'Print / PDF',
  'Du bist früher als geplant.': 'You are earlier than planned.', 'Du bist später als geplant.': 'You are later than planned.', 'Du gehst früher als geplant.': 'You are leaving earlier than planned.',
  'Du hast länger gearbeitet als geplant.': 'You worked longer than planned.', 'E-Mail': 'E-mail', 'E-Mail oder Benutzername': 'E-mail or username',
  'E-Mail-Benachrichtigungen': 'E-mail notifications', Eingestempelt: 'Clocked in', 'Eingestempelt {time}': 'Clocked in {time}',
  'Eingestempelt {t}, nie ausgestempelt': 'Clocked in {t}, never clocked out', Einstempeln: 'Clock in', 'Eintrag nachtragen': 'Add a missing entry', Eintragen: 'Assign',
  Eintritt: 'Start date', 'Endgültig löschen': 'Delete permanently', Entkoppeln: 'Unpair', 'Entsperrt.': 'Unlocked.', Entwurf: 'Draft', 'Erster Tag halbtags': 'First day half day',
  'Erwartet, nicht da': 'Expected, not arrived', 'Es gibt noch Zeiten, die auf Freigabe warten.': 'Some times are still waiting for approval.',
  'Es werden Entwürfe erzeugt; Abwesenheiten und bestehende Einträge werden übersprungen.': 'Drafts are created; absences and existing entries are skipped.',
  'Etwas ist schiefgelaufen.': 'Something went wrong.', Fertig: 'Done', Format: 'Format', Fr: 'Fri', 'Frage an die Leitung': 'Ask a manager', 'Frage senden': 'Send question',
  Fragen: 'Questions', Frei: 'Off', 'Freigabe nötig': 'Approval needed', 'Freigabe offen': 'Approval open', Freigeben: 'Approve', Freigegeben: 'Approved', Freiwunsch: 'Day-off wish',
  'Früh ausgestempelt': 'Clocked out early', 'Früh eingestempelt': 'Clocked in early', Fälle: 'Cases',
  'Für dich ist heute kein Dienst geplant. Bitte gib einen Grund an – deine Leitung muss die Zeit freigeben.': 'No shift is planned for you today. Please give a reason – your manager must approve the time.',
  Gearbeitet: 'Worked', Geburtsdatum: 'Date of birth', Gehalt: 'Salary', 'Gehalt (Arbeitszeitkonto)': 'Salary (time account)', Gelesen: 'Read', Genehmigen: 'Approve',
  'Genehmigen?': 'Approve?', Genehmigt: 'Approved', Genommen: 'Taken', Geplant: 'Planned', 'Geplante Dienste an diesen Tagen entfernen': 'Remove planned shifts on these days',
  'Gerade ist keine Aktion möglich. Bitte die Leitung fragen.': 'No action is possible right now. Please ask your manager.', 'Gerade niemand eingestempelt.': 'Nobody is clocked in right now.',
  Geschlossen: 'Closed', 'Gespeichert.': 'Saved.', 'Gesperrt bis einschließlich': 'Locked up to and including', 'Gesperrt bis {d}.': 'Locked until {d}.', Grund: 'Reason',
  'Grund (optional)': 'Reason (optional)', Gutschrift: 'Credit', 'Gültig bis {t}. Auf dem Tablet unter /kiosk eingeben.': 'Valid until {t}. Enter it on the tablet at /kiosk.',
  'Hallo {name}': 'Hello {name}', 'Hat an Feiertagen frei (Gutschrift)': 'Has public holidays off (credited)', Hauptnavigation: 'Main navigation', Herunterladen: 'Download',
  Heute: 'Today', 'Heute gearbeitet: {m} Min.': 'Worked today: {m} min.', 'Heute ist kein Dienst geplant.': 'No shift planned today.', Hinweise: 'Notes', Hotel: 'Hotel',
  'In der Pause': 'On break', Jahresanspruch: 'Yearly entitlement', Jugendschutz: 'Youth protection', 'Jugendschutz (Uhrzeit)': 'Youth protection (time of day)',
  'Keine Einträge sichtbar.': 'No entries visible.', 'Keine Einträge.': 'No entries.', 'Keine Fragen.': 'No questions.', 'Keine Hinweise für diese Woche.': 'No notes for this week.',
  'Keine Mitarbeitenden.': 'No employees.', 'Keine Mitteilungen.': 'No notifications.', 'Keine offenen Abwesenheiten.': 'No open absences.', 'Keine offenen Korrekturen.': 'No open corrections.',
  'Keine offenen Prüfungen.': 'No open reviews.', 'Keine offenen Wünsche.': 'No open wishes.', 'Keine weiteren Dienste veröffentlicht.': 'No further shifts published.',
  'Kolleg:innen ausblenden': 'Hide colleagues', 'Konto aktivieren': 'Activate account', Koppeln: 'Pair', Kopplungscode: 'Pairing code', 'Kopplungscode erzeugen': 'Create pairing code',
  'Korrektur entschieden': 'Correction decided', Korrigieren: 'Correct', Krank: 'Sick', 'Krank melden': 'Report sick', Krankenquote: 'Sick rate', Krankenstand: 'Sickness',
  Krankheitstage: 'Sick days', 'Krankmeldung eingegangen': 'Sick report received', Kurzfristig: 'Short notice', 'Letzte 30 Tage': 'Last 30 days', 'Letzter Tag halbtags': 'Last day half day',
  'Link senden': 'Send link', Live: 'Live', 'Live-Übersicht': 'Live overview', 'Lohn-Export': 'Payroll export', 'Lädt …': 'Loading …', Löschen: 'Delete',
  'Mehr als der Jahresanspruch': 'More than the yearly entitlement', 'Mein Dienstplan': 'My roster', 'Mein Portal': 'My portal', 'Meine Anträge': 'My requests',
  'Meine Daten': 'My data', 'Meine Korrekturen': 'My corrections', 'Meine Zeiten': 'My times', Mi: 'Wed', Minijob: 'Mini job', 'Mit Korrektur schließen': 'Close with correction',
  Mitarbeiter: 'Staff', 'Mitarbeiter anlegen': 'Add employee', 'Mitarbeiter löschen?': 'Delete employee?', Mitteilungen: 'Notifications', Mo: 'Mon', Monat: 'Month',
  'Mögliche Vertretung': 'Possible cover', Nachname: 'Last name', Nachricht: 'Message', 'Nachricht …': 'Message …', Name: 'Name', 'Name des Tablets': 'Tablet name',
  'Name suchen': 'Search name', 'Name suchen …': 'Search name …', 'Neue Frage': 'New question', 'Neue Frage von einem Mitarbeitenden': 'New question from an employee',
  'Neue PIN': 'New PIN', 'Neue PIN (6 Ziffern)': 'New PIN (6 digits)', 'Neue Zeitkorrektur zur Prüfung': 'New time correction to review', 'Neuer Abwesenheitsantrag': 'New absence request',
  'Neuer Antrag': 'New request', 'Neuer Dienstplan veröffentlicht': 'New roster published', 'Neuer Wunsch': 'New wish', 'Neues Passwort': 'New password', 'Nicht da': 'Not in', 'Niemand gefunden.': 'Nobody found.', 'Gerade ist kein Dienst in Sicht. Tippe deinen Namen, um dich einzustempeln.': 'No shift is due right now. Type your name to clock in.',
  'Nicht eingestempelt': 'Not clocked in', 'Nicht erschienen': 'No-show', 'Nichts zur Freigabe.': 'Nothing to approve.', 'Noch kein Tablet gekoppelt.': 'No tablet paired yet.',
  'Noch keine Anträge.': 'No requests yet.', 'Noch nichts gesperrt.': 'Nothing locked yet.', 'Notiz (optional)': 'Note (optional)', 'Nr.': 'No.', 'Nächste Dienste': 'Next shifts',
  'Nächste Woche': 'Next week', 'Nächstes Jahr': 'Next year', Offen: 'Open',
  'Ohne E-Mail-Adresse: Bitte deine Leitung um einen Link zum Zurücksetzen.': 'Without an e-mail address: please ask your manager for a reset link.',
  'PIN entsperren': 'Unlock PIN', 'PIN falsch. Noch {n} Versuche.': 'Wrong PIN. {n} attempts left.', 'PIN gesperrt bis {time}. Bitte die Leitung fragen.': 'PIN locked until {time}. Please ask your manager.',
  'PIN geändert.': 'PIN changed.', 'PIN zurücksetzen': 'Reset PIN', 'PIN ändern': 'Change PIN', 'PIN-Eingabe': 'PIN entry', Passwort: 'Password', 'Passwort geändert.': 'Password changed.',
  'Passwort geändert. Du kannst dich jetzt anmelden.': 'Password changed. You can sign in now.', 'Passwort vergessen?': 'Forgot password?', 'Passwort wiederholen': 'Repeat password',
  'Passwort zurücksetzen': 'Reset password', 'Passwort ändern': 'Change password', Pause: 'Break', 'Pause (Minuten)': 'Break (minutes)', 'Pause beenden': 'End break',
  'Pause fehlt': 'Break missing', 'Pause fehlt.': 'Break missing.', 'Pause starten': 'Start break', Personalnummer: 'Personnel no.', Personen: 'People', Praktikum: 'Internship',
  Profil: 'Profile', 'Prüfe Regeln …': 'Checking rules …', Prüfen: 'Check', Prüfung: 'Review', Quote: 'Rate',
  'Reduzierte Ansicht: Stundenlohn, Kontaktdaten und Abwesenheitsarten sieht nur die Leitung des Stammhauses.': 'Reduced view: only the home hotel manager sees hourly rate, contact data and absence types.',
  'Rest aus dem Vorjahr': 'Left from last year', 'Resturlaub {a} → {b}': 'Vacation left {a} → {b}', Rezeption: 'Front desk', 'Richtige Ausstempelzeit': 'Correct clock-out time',
  Sa: 'Sat', Saldo: 'Balance', Schichtwunsch: 'Shift wish', Schließen: 'Close', 'Schon genommen: {n} Tage': 'Already taken: {n} days', 'Schon vor dem Start genommen': 'Already taken before start',
  Senden: 'Send', Serverzeit: 'Server time', So: 'Sun', Soll: 'Target', Sollzeiten: 'Target hours', 'Sollzeiten speichern': 'Save target hours', Sonstige: 'Other', Sonstiges: 'Other',
  Speichern: 'Save', Sperren: 'Lock', Sprache: 'Language', Springer: 'Floating', Stammdaten: 'Master data', Stammhaus: 'Home hotel', Status: 'Status', 'Stempel-Tablets': 'Clock-in tablets',
  Stempelkorrekturen: 'Clock corrections', Stempeluhr: 'Time clock', 'Stempelzeit korrigieren': 'Correct a clock time', Stunden: 'Hours', 'Stunden vs. Soll': 'Hours vs. target',
  Stundenlohn: 'Hourly wage', 'Stundenlohn (€)': 'Hourly wage (€)', 'Stundenlohn: kein Arbeitszeitkonto.': 'Hourly wage: no time account.', Suche: 'Search', Tablet: 'Tablet',
  'Tablet & Export': 'Tablet & Export', 'Tablet einrichten': 'Set up tablet', 'Tablet-PIN': 'Tablet PIN', Tage: 'days', 'Tage übrig': 'days left', Tageshöchstzeit: 'Daily maximum',
  Teilzeit: 'Part time', Telefon: 'Phone', Thema: 'Topic', Unbezahlt: 'Unpaid', Ungeplant: 'Unplanned',
  'Ungeplant gearbeitete Zeiten zählen erst nach deiner Freigabe.': 'Unplanned working times only count after your approval.', 'Ungeplante Arbeitszeit': 'Unplanned working time',
  'Ungeplanter Dienst – deine Leitung prüft die Zeit.': 'Unplanned shift – your manager will review the time.', Unterbesetzt: 'Understaffed',
  'Unterbesetzt am {d}, falls genehmigt': 'Understaffed on {d} if approved', Urlaub: 'Vacation', 'Urlaub & Abwesenheit': 'Vacation & absence', 'Urlaub (Startwerte)': 'Vacation (starting values)',
  'Urlaub beantragen': 'Request vacation', 'Urlaub speichern': 'Save vacation', 'Urlaub {y}': 'Vacation {y}', 'Urlaubstage pro Jahr': 'Vacation days per year', Urlaubswunsch: 'Leave wish',
  Vergütung: 'Pay', Verspätungen: 'Late arrivals', Veröffentlichen: 'Publish', Veröffentlicht: 'Published', Vollzeit: 'Full time', Von: 'From', 'Von – bis': 'From – to',
  'Vorherige Woche': 'Previous week', Vorjahr: 'Previous year', Vorname: 'First name', Warnung: 'Warning', Warnungen: 'Warnings', 'Wartet auf Freigabe': 'Awaiting approval',
  'Wenn ein Konto zu dieser E-Mail-Adresse existiert, ist ein Link unterwegs.': 'If an account exists for this e-mail address, a link is on its way.', 'Wer arbeitet noch?': 'Who else is working?',
  Werkstudent: 'Working student', 'Wieder öffnen': 'Reopen', 'Wird nur jetzt angezeigt. Bitte der Person persönlich mitteilen.': 'Shown only now. Please tell the person in person.',
  'Woche kopieren': 'Copy week', 'Woche {n}': 'Week {n}', 'Wunsch entschieden': 'Wish decided', 'Während Abwesenheit': 'During absence', Wünsche: 'Wishes',
  'Zeiteintrag braucht Prüfung': 'Time entry needs review', 'Zeiteintrag korrigieren': 'Correct time entry', Zeiten: 'Times', Zeiterfassung: 'Time tracking', 'Zeitraum sperren': 'Lock period',
  'Zielwoche beginnt am (Montag)': 'Target week starts on (Monday)', 'Zu den Anträgen': 'To the requests', 'Zu prüfen': 'To review', 'Zu spät eingestempelt': 'Clocked in late',
  'Zurück zur Anmeldung': 'Back to sign-in', Zurückgezogen: 'Withdrawn', Zurückziehen: 'Withdraw', automatisch: 'automatic', entkoppelt: 'unpaired',
  'geplant {p} · Soll {s}': 'planned {p} · target {s}', 'kein Dienst geplant': 'no shift planned', 'leer': 'empty', 'läuft noch': 'still running', manuell: 'manual',
  'mindestens 10 Zeichen': 'at least 10 characters', 'nicht verfügbar': 'unavailable', 'noch nicht ausgestempelt': 'not clocked out yet', 'noch nie benutzt': 'never used',
  offen: 'open', 'seit {t}': 'since {t}', ungelesen: 'unread', ungeplant: 'unplanned', 'verfällt am {d}': 'expires on {d}', veröffentlicht: 'published', 'von {n} Tagen im Jahr': 'of {n} days a year',
  'z. B. Kollegin krank, Aushilfe …': 'e.g. colleague sick, cover …', '{a} Abwesenheiten · {b} Wünsche · {c} Korrekturen · {d} Fragen offen': '{a} absences · {b} wishes · {c} corrections · {d} questions open',
  '{a} {time}': '{a} {time}', '{n} Entwürfe': '{n} drafts', '{n} Min. zu spät': '{n} min late', '{n} Tage': '{n} days', '{n} Tage beantragt': '{n} days requested',
  '{n} geplante Dienste an diesen Tagen.': '{n} planned shifts on these days.', '{n} kopiert, {m} übersprungen.': '{n} copied, {m} skipped.', '{n} offen': '{n} open', '{n} ungelesen': '{n} unread',
  Änderung: 'Change', 'Überall abmelden': 'Sign out everywhere', Übersicht: 'Overview', 'Übersprungen: {x}': 'Skipped: {x}', Überstunden: 'Overtime', Übertrag: 'Carry-over',
  'Übertrag (Tage)': 'Carry-over (days)', 'Übertrag aus Vorjahr': 'Carry-over from last year', 'Übertrag aus dem Vorjahr automatisch berechnen': 'Calculate carry-over from last year automatically',
  'Übertrag verfällt am': 'Carry-over expires on', Übrig: 'Left', 'unter Soll': 'below target', 'im Soll': 'on target', 'über Soll': 'above target', 'über Maximum': 'above maximum', '– wählen –': '– select –', '← Zur Anmeldung': '← Back to sign-in',
  'Administration': 'Administrator',
  'Aktion': 'Action',
  'Aktion (genau, z. B. shift.create)': 'Action (exact, e.g. shift.create)',
  'Aktivieren': 'Enable',
  'Anlegen & Link erzeugen': 'Create & generate link',
  'Anmeldung': 'Sign-in',
  'Arbeiten': 'Work',
  'Art des Wunsches': 'Type of wish',
  'Beginn': 'Start',
  'Benutzer': 'Users',
  'Benutzer anlegen': 'Add user',
  'Bereich': 'Section',
  'Bezahlt': 'Paid',
  'Die Person legt ihr Passwort selbst über den Link fest.': 'The person sets their own password via the link.',
  'Dienst (optional)': 'Shift (optional)',
  'Dienst bearbeiten': 'Edit shift',
  'Dienste': 'Shifts',
  'Dienste werden von der Administration angelegt. Du kannst den Mindestbedarf festlegen.': 'Shifts are created by the administration. You can set the minimum staffing.',
  'Einladungslink': 'Invitation link',
  'Einrichtung': 'Setup',
  'Ende': 'End',
  'Endet der Dienst vor dem Beginn, geht er über Mitternacht.': 'If the shift ends before it starts, it runs past midnight.',
  'Farbe': 'Colour',
  'Gehört zu Mitarbeiter': 'Belongs to employee',
  'Hinzufügen': 'Add',
  'Hotels': 'Hotels',
  'Hotelzugang': 'Hotel access',
  'Keine Sperren.': 'No blackouts.',
  'Leitung': 'Manager',
  'Link': 'Link',
  'Link zum Zurücksetzen': 'Reset link',
  'Mindestbesetzung': 'Minimum staffing',
  'Mindestbesetzung: {name}': 'Minimum staffing: {name}',
  'Möchte arbeiten': 'Wants to work',
  'Möchte nicht arbeiten': 'Does not want to work',
  'Neuer Dienst': 'New shift',
  'Noch keine Dienste.': 'No shifts yet.',
  'Noch keine Wünsche.': 'No wishes yet.',
  'Objekt': 'Object',
  'Passwort-Link': 'Password link',
  'Planungswünsche': 'Planning wishes',
  'Protokoll': 'Audit log',
  'Rolle': 'Role',
  'Schicht- oder Freiwunsch': 'Shift or day-off wish',
  'Seite {p} von {n}': 'Page {p} of {n}',
  'Urlaubssperren': 'Leave blackouts',
  'Warnen': 'Warn',
  'Wichtigkeit': 'Priority',
  'Wie viele Personen müssen an welchem Wochentag mindestens eingeplant sein? 0 = kein Bedarf.': 'How many people must be rostered at least on which weekday? 0 = no requirement.',
  'Wird nur einmal angezeigt. Gültig bis {d}.': 'Shown only once. Valid until {d}.',
  'Wirkung': 'Effect',
  'Wunsch gesendet.': 'Wish sent.',
  'Wunsch senden': 'Send wish',
  'Wünsche helfen bei der Planung – deine Leitung entscheidet.': 'Wishes help with planning – your manager decides.',
  'Zeit': 'Time',
  'Zeiträume (z. B. Messewochen), in denen Urlaubsanträge gewarnt oder gesperrt werden.': 'Periods (e.g. trade-fair weeks) in which leave requests are warned about or blocked.',
  'ganzer Tag': 'whole day',
  'hoch': 'high',
  'mittel': 'medium',
  'niedrig': 'low',
  'aktiv': 'active',
  'eingeladen': 'invited',
  'gesperrt': 'locked',
  'Springer können in mehreren Hotels eingeplant werden. Das Stammhaus pflegt Daten, Lohn und Urlaub.': 'Floating staff can be rostered at several hotels. The home hotel maintains data, pay and vacation.',
  'Hotels speichern': 'Save hotels',
  'Aktionen': 'Actions',
  'Hotel wählen': 'Choose hotel',
  'PIN gesperrt. Bitte die Leitung fragen.': 'PIN locked. Please ask your manager.',
  'Abwesenheit': 'Absence',
  'Arbeitszeitrecht': 'Working-time law',
  'Aufbewahrung': 'Retention',
  'Begründung zum Übergehen verlangen': 'Require a reason to override',
  'Beim Einplanen auf Unterschreitung des Solls hinweisen': 'Warn when assigning would stay below target',
  'Beraternummer': 'Consultant number',
  'DATEV-Produkt': 'DATEV product',
  'Dienstplan sichtbar für Mitarbeitende': 'Roster visible to employees',
  'Einstellungen kann nur die Administration ändern.': 'Only the administration can change settings.',
  'Einstellungen speichern': 'Save settings',
  'Entfernen': 'Remove',
  'Fragen aufbewahren (Monate)': 'Keep questions (months)',
  'Früh einstempeln erlaubt (Min.)': 'Early clock-in allowed (min.)',
  'Frühester Beginn': 'Earliest start',
  'Hoteleinstellungen': 'Hotel settings',
  'Höchstarbeitszeit prüfen': 'Check maximum working time',
  'Höchstens Dienste pro Tag': 'Maximum shifts per day',
  'Höchstens Tage pro Woche': 'Maximum days per week',
  'Höchstzeit pro Tag (Std.)': 'Maximum per day (h)',
  'Höchstzeit pro Woche (Std.)': 'Maximum per week (h)',
  'Höchstübertrag (Tage, leer = unbegrenzt)': 'Maximum carry-over (days, empty = unlimited)',
  'Krankheitstage mit Stundengutschrift (max.)': 'Sick days with hours credit (max.)',
  'Krankschreibung ab Tag': 'Medical certificate from day',
  'Kurzfristig: Änderungen weniger als … Stunden vor Dienstbeginn': 'Short notice: changes less than … hours before the shift starts',
  'Lohnart: Arbeitszeit': 'Wage type: worked time',
  'Lohnart: Berufsschule': 'Wage type: vocational school',
  'Lohnart: Feiertag (Gutschrift)': 'Wage type: public holiday (credit)',
  'Lohnart: Feiertag (Zuschlag)': 'Wage type: public holiday (supplement)',
  'Lohnart: Krank': 'Wage type: sick',
  'Lohnart: Nacht': 'Wage type: night',
  'Lohnart: Samstag': 'Wage type: Saturday',
  'Lohnart: Sonntag': 'Wage type: Sunday',
  'Lohnart: Urlaub': 'Wage type: vacation',
  'Längste Schichtspanne (Std.)': 'Longest shift span (h)',
  'Längste Tagesspanne bei geteilten Diensten (Std.)': 'Longest day span for split shifts (h)',
  'Mandantennummer': 'Client number',
  'Min. Pause': 'min. break',
  'Minuten Pause': 'Break minutes',
  'Mitarbeiterportal': 'Employee portal',
  'Muster aus der Lohnbuchhaltung übernehmen': 'Copy the sample from the payroll office',
  'Nachtzuschlag ab': 'Night supplement from',
  'Nachtzuschlag bis': 'Night supplement until',
  'Namen von Kolleg:innen': 'Colleagues’ names',
  'Offene Einträge nach … Std. zur Prüfung': 'Open entries go to review after … h',
  'PIN: Fehlversuche bis zur Sperre': 'PIN: failed attempts before lock',
  'PIN: Sperrdauer (Min.)': 'PIN: lock duration (min.)',
  'Pausen': 'Breaks',
  'Pausenregeln (Bruttozeit)': 'Break rules (gross time)',
  'Pausenregeln (Nettozeit)': 'Break rules (net time)',
  'Regel hinzufügen': 'Add rule',
  'Ruhezeit (Std.)': 'Rest period (h)',
  'Ruhezeit zwischen Diensten (Std.)': 'Rest period between shifts (h)',
  'Spätestes Ende': 'Latest end',
  'Spätestes Ende ab 16 (Gastronomie)': 'Latest end from 16 (hospitality)',
  'Std. mindestens': 'h at least',
  'Tablet nur von diesen IP-Adressen (kommagetrennt, leer = alle)': 'Tablet only from these IP addresses (comma-separated, empty = any)',
  'Toleranz Verspätung (Min.)': 'Tolerance for lateness (min.)',
  'Toleranz Überstunden (Min.)': 'Tolerance for overtime (min.)',
  'Urlaubsübertrag verfällt am (MM-TT, leer = nie)': 'Vacation carry-over expires on (MM-DD, empty = never)',
  'Vergessenes Ausstempeln: Plan-Zeit nach … Std. gutschreiben (leer = aus)': 'Forgotten clock-out: credit planned time after … h (empty = off)',
  'Verstöße': 'Violations',
  'Vorlage Kopfzeile': 'Header template',
  'Vorlage Satzbeschreibung': 'Record description template',
  'Vorlage Zeile': 'Line template',
  'Vorname + Initiale': 'First name + initial',
  'Wünsche frühestens … Tage vorher (leer = beliebig)': 'Wishes at least … days ahead (empty = any)',
  'Zeichensatz': 'Character set',
  'Zeiterfassung aufbewahren (Jahre)': 'Keep time records (years)',
  'ab mehr als': 'over',
  'am Tablet erfassen': 'record on the tablet',
  'automatisch abziehen': 'deduct automatically',
  'blockieren': 'block',
  'eigene Abteilungen': 'own departments',
  'ganzes Hotel': 'whole hotel',
  'nur eigene Dienste': 'own shifts only',
  'pro Tag': 'per day',
  'pro Woche': 'per week',
  'voller Name': 'full name',
  'warnen': 'warn',
  'z. B. 03-31': 'e.g. 03-31',
  'Für den DATEV-Export fehlen die Berater- und Mandantennummer.': 'The DATEV export needs the consultant and client number.',
  'Bitte unter Einrichtung → Hoteleinstellungen → Lohn-Export eintragen (nur Administration).': 'Please enter them under Setup → Hotel settings → Payroll export (administration only).',
  'Zur Einrichtung': 'Go to setup',
  'LODAS: Die Lohnarten sind Vorschläge (2000 Arbeitszeit, 2010 Urlaub …). Beim ersten Import im DATEV-Testmandanten prüfen und in den Hoteleinstellungen anpassen.': 'LODAS: the wage types are suggestions (2000 worked time, 2010 vacation …). Check them on the first import in a DATEV test client and adjust them in the hotel settings.',
  'Vorschlag 2000; leer = Vorschlag': 'Suggestion 2000; empty = suggestion',
  'Pflicht für den DATEV-Export': 'Required for the DATEV export',
  Feiertage: 'Public holidays',
  'Excel-Tabelle (.xlsx)': 'Excel table (.xlsx)',
  Datenschutz: 'Data protection',
  Anonymisiert: 'Anonymised',
  Anonymisieren: 'Anonymise',
  'Mitarbeiter anonymisieren?': 'Anonymise employee?',
  'Endgültig anonymisieren': 'Anonymise permanently',
  'Ersetzt Name, Kontaktdaten, Stundenlohn, Geburtsdatum, Personalnummer, PIN und Login durch neutrale Platzhalter. Dienstplan, Abwesenheiten und Zeiten bleiben für die Aufbewahrung erhalten. Das kann nicht rückgängig gemacht werden.': 'Replaces name, contact details, hourly rate, birth date, personnel number, PIN and login with neutral placeholders. Roster, absences and time records are kept for the retention period. This cannot be undone.',
  'Auch Rückfragen dieser Person werden gelöscht. Das Protokoll bleibt unverändert.': 'This person\'s inquiries are deleted as well. The audit log stays unchanged.',
  'Die Aufbewahrungsfrist endet am {d}. Eine vorzeitige Anonymisierung ist nur auf Verlangen sinnvoll (z. B. Löschanspruch nach DSGVO); die Begründung wird protokolliert.': 'The retention period ends on {d}. Anonymising early only makes sense on request (e.g. a GDPR erasure claim); the reason is logged.',
  Jahr: 'Year',
  'Keine Feiertage.': 'No public holidays.',
  'Gesetzliche Feiertage der Region des Hotels. Sie werden bei Abwesenheiten, Gutschriften und Zuschlägen berücksichtigt.': 'Public holidays of the hotel\'s region. They are taken into account for absences, credits and supplements.',
};
